# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='buzz',
            name='text',
            field=models.TextField(max_length=140),
        ),
    ]
