# Generated by Django 2.1.2 on 2018-11-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzz',
            name='file',
            field=models.FileField(blank=True, upload_to='buzzfile', verbose_name='Buzz File'),
        ),
    ]
