# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0002_auto_20181110_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='buzzer_logo.png', upload_to='media', verbose_name='Image'),
        ),
    ]
