# Generated by Django 2.1.2 on 2018-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0003_auto_20181110_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzz',
            name='image',
            field=models.ImageField(blank=True, upload_to='buzzmedia', verbose_name='Buzz Image'),
        ),
    ]
